name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Dynamic Array Tests
      id: dynamic-array-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Dynamic Array Tests
        setup-command: gradle build
        command: "./gradlew :app:test --tests DynamicArrayTests"
        timeout: 3
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DYNAMIC-ARRAY-TESTS_RESULTS: "${{steps.dynamic-array-tests.outputs.result}}"
      with:
        runners: dynamic-array-tests
